### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by matjazpotocnik** [BlowbackDesign/TinyPNG#1]
Warning: require_once(C:/inetpub/wwwroot/site/modules/TinyPNG/tinify-php/lib/Tinify/Exception.php): failed to open stream: No such file or directory in C:\inetpub\wwwroot\site\assets\cache\FileCompiler\site\modules\TinyPNG\TinyPNG.module on line 66

I clicked "Download ZIP" and the zip file does not include tinify-png files.

**Comment by Roope** [comment]
Hello and thanks for the info! It looks like git submodule files are not included in zip - didn't know. Have to think something else to replace it. In the meantime you are limited to use git or include tinify-php files manually.

git clone --recursive https://github.com/BlowbackDesign/TinyPNG
https://desktop.github.com
https://github.com/tinify/tinify-php/archive/master.zip

**Comment by Roope** [comment]
OK, tiny-png submodule removed and merged as remote subtree - all files should be now included within zip file.
